### ISSUE TITLE
All videos not showing??

### ISSUE THREAD

**Issue by mberube510** [GuardianTheater/guardian-theater-indexeddb#44]
I have linked my bungie and twitch accounts, but I'm only getting about 10 videos to show even though there are 145 listed in the top window? Am I missing something? Thanks in advance

**Comment by chrisfried** [comment]
"getVideos - 145" means it fetched VODs from 145 Twitch accounts to see if any matched up to when you played against them. If it is only showing you 10 videos, it only found 10 videos in those VOD lists.
