### ISSUE TITLE
No videos showing

### ISSUE THREAD

**Issue by ImmGib** [GuardianTheater/guardian-theater-indexeddb#54]
I know I've played with streamers but none of the vods are showing up even after hard and soft resetting multiple times

**Comment by chrisfried** [comment]
How recently did you encounter the streamer(s)? Are you sure they were streaming at the time?

If you let me know your Bungie account and the streamer(s) you encountered, I can investigate this further.

**Comment by ImmGib** [comment]
So, the streamers name was Azpharion and I play with him within the past
week and he was streaming that's just how I'm confused also I'm bungie Id
is ImGib#6035

**Comment by ImmGib** [comment]
Also the streamers bungie id is AzPharizon#5232 I mightve misspelled his gt
in the prior email, my apologies

**Comment by chrisfried** [comment]
Do you have a link to the PGCR? I'm not finding an activity with both ImGib#6035 and AzPharizon#5232 in the past 60 days.

I do see a video from HoundOfTheSidh#5362 from yesterday when viewing GT from your perspective, so it's not that the site isn't showing you _any_ videos.

**Comment by ImmGib** [comment]
https://www.twitch.tv/azpharizon/v/1216089298?sr=a&t=6218s

This if from a week ago show both me and azpharizon in orbit and then into
a game also we played multiple games before this one. But none are showing
up

**Comment by chrisfried** [comment]
Thanks, that helped diagnose the issue. I'll get a fix ready sometime this week.
