### ISSUE TITLE
Xbox Clips Error

### ISSUE THREAD

**Issue by DropTryy** [GuardianTheater/guardian-theater-indexeddb#56]
Upon logging in to both twitch and steam the xbox clips say "Error" for every single clip generation attempt.
![xbox error](https://user-images.githubusercontent.com/63314558/145885600-31318ace-0eb3-4ed7-a7bf-3337ee63e75a.JPG)

**Comment by chrisfried** [comment]
Thanks, we're investigating.

**Comment by chrisfried** [comment]
Required authentication should be minimizing the number of errored responses you encounter.
