### ISSUE TITLE
New Videos Not Showing Up

### ISSUE THREAD

**Issue by SyonaR** [GuardianTheater/guardian-theater-indexeddb#57]
Hey there! for weeks I've had an issue where, inconsistently, new and old videos aren't showing. A couple weeks ago, for example, I played in trials with a streamer friend of mine, and none of those clips are popping up. The only ones that are showing are one from early November, and then a few from October. I had a bunch before then and a bunch in between all of them. I've tried unlinking my Twitch account to my Bungie account and that didn't fix anything. Do you know what the issue could be?

**Comment by chrisfried** [comment]
Does your streamer friend have their Twitch account linked to their Bungie account? What’s their BungieName#1234?
