### ISSUE TITLE
“Xbox Clip API overloaded, try again later”

### ISSUE THREAD

**Issue by Ryse-Sticks** [GuardianTheater/guardian-theater-indexeddb#58]
![D5EF1DFE-22B3-48AD-8CB3-1F10626E5B7D](https://user-images.githubusercontent.com/96286458/146515180-0b5619f3-0ad6-4584-bed3-4f7e45451df2.jpeg)
![D008A126-8C3B-434B-87A4-0E7204D15B59](https://user-images.githubusercontent.com/96286458/146515182-28249031-0557-4dc8-ac1b-68a10304f790.jpeg)

**Comment by GeekyNerdFTW** [comment]
Same for me

**Comment by chrisfried** [comment]
With the required authentication, you should hit the "API overloaded" message much less frequently.
