### ISSUE TITLE
Issue Xbox login - error message

### ISSUE THREAD

**Issue by Nandrix** [GuardianTheater/guardian-theater-indexeddb#73]
I'm getting an error message trying to log in with Xbox on the site. I get this error message when I click on "Xbox login" ""message":"Something went wrong"}"

Chrome console message: "auth:1 Unchecked runtime.lastError: The message port closed before a response was received."

[URL](https://xapi.dustinrue.com/auth?code=M.R3_BL2.83bfd519-a955-dca4-b13e-8a3fbef0bb87&client_info=eyJ2ZXIiOiIxLjAiLCJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBeGp2MHRyOEdLXy1PUXVxWGRJSEEwIiwibmFtZSI6IkVyaWMgR3VzdGFmc3NvbiIsInByZWZlcnJlZF91c2VybmFtZSI6ImVyLWd1c0Bob3RtYWlsLmNvbSIsIm9pZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC1hMTgyLWFjMzQxYzhkNDAwYyIsInRpZCI6IjkxODgwNDBkLTZjNjctNGM1Yi1iMTEyLTM2YTMwNGI2NmRhZCIsImhvbWVfb2lkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLWExODItYWMzNDFjOGQ0MDBjIiwidWlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLWExODItYWMzNDFjOGQ0MDBjIiwidXRpZCI6IjkxODgwNDBkLTZjNjctNGM1Yi1iMTEyLTM2YTMwNGI2NmRhZCJ9)

Please have a look :)
Thanks for a great tool!

**Comment by seancoyne** [comment]
I am also seeing this when using the Xbox Login feature

**Comment by ColossaI** [comment]
@chrisfried @dustinrue any further update on this issue? I've been seeing it for the past week now and have been unable to see any Xbox clips because of it

**Comment by chrisfried** [comment]
Yes, I think I figured out the issue this morning, I just need to have Dustin update a key on his end when he has a minute.

**Comment by ColossaI** [comment]
@chrisfried great news! thanks for the update

**Comment by chrisfried** [comment]
Should be working again! Thanks, @dustinrue.
